Repository RubberDuckCrew/gitdone, pull requests merged in 2025-08, with the labels that each got.

#162 🐛 Fix Alphabetical Sorting
  lib/ui/task_list/task_list_view_model.dart
Labels: 🐛 Bug

#161 💄 Add monochrome app icons and improve normal ones
  android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/values-night/styles.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  assets/icons/app/MonochromeLogo.svg
  assets/icons/app/gitdone-monochrome.svg
  assets/icons/app/gitdone-monochrome@2000.png
  assets/icons/app/gitdone@1000.png
  assets/icons/app/gitdone@250.png
  assets/icons/app/gitdone@500.png
  pubspec.lock
  pubspec.yaml
Labels: 💄 UI/UX

#176 ✨Edit labels of task
  lib/core/task_handler.dart
  lib/ui/task_details/task_details_view.dart
  lib/ui/task_edit/task_edit_view.dart
  lib/ui/task_edit/task_edit_view_model.dart
  lib/ui/task_list/task_list_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Enhancement

#178 ✨ Add OAuthPKCE
  android/app/src/main/AndroidManifest.xml
  assets/imgs/sadDuck.png
  lib/core/exceptions/oauth_exception.dart
  lib/core/models/github_oauth_model.dart
  lib/ui/login/oauth/login_oauth_screen.dart
  lib/ui/login/oauth/login_oauth_view.dart
  lib/ui/login/oauth/login_oauth_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Enhancement

#184 :bug: Update navigation to use clean transition to MainScreen after login
  lib/ui/login/oauth/login_oauth_view_model.dart
Labels: 🐛 Bug

#181 :bug: Fix infinite loading
  lib/ui/task_list/task_list_view.dart
  lib/ui/task_list/task_list_view_model.dart
Labels: 🐛 Bug

#194 🔧 Update reviewers to new gitdone development team
  .github/renovate.json
Labels: 🔧 Configuration

#197 📝 Create CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: 📝 Documentation

#200 📝 Update coventions url to pages docs
  README.md
Labels: 📝 Documentation

#204 👷 Add actionlint workflow
  .github/workflows/actionlint.yml
  .github/workflows/test-build-release.yml
Labels: 👷 CI/CD
