Repository RubberDuckCrew/gitdone, pull requests merged in 2025-04, with the labels that each got.

#26 🔀⬆️ Update NDK version to 27.2.12479018 in build.gradle
  android/app/build.gradle
Labels: 🛠️ Maintenance

#27 🔀👷 Add app signing in github action
  .github/workflows/build.yml
  android/app/build.gradle
Labels: 🛠️ Maintenance

#28 🔀📝 Create SECURITY.md
  .github/SECURITY.md
Labels: 📝 Documentation

#31 📝 Update issue templates
  .github/ISSUE_TEMPLATE/✨feature-request.md
Labels: 📝 Documentation

#34 🔧 Add bug report template and adjust feature template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: 🛠️ Maintenance

#35 📄 Update copyright holder in LICENSE file
  LICENSE
Labels: 📝 Documentation, 🛠️ Maintenance

#38 💚 Update enforce-labels workflow to use regex for label m…
  .github/workflows/enforce-labels.yml
Labels: 🛠️ Maintenance

#32 🔀👷 Update workflows to use github_flutter package
  .github/workflows/build.yml
  .github/workflows/test.yml
  pubspec.lock
  pubspec.yaml
Labels: 🛠️ Maintenance

#36 📝 Update README.md
  README.md
Labels: 📝 Documentation

#44 ♻️ Switch to github app
  lib/core/models/github_oauth_model.dart
Labels: ♻️ Refactor

#42 🧑‍💻Change App Structure and first use of MVVM Pattern
  lib/app.dart
  lib/core/github_api_handler.dart
  lib/core/models/github_oauth_model.dart
  lib/core/models/token_handler.dart
  lib/core/theme/app_color.dart
  lib/ui/_widgets/app_bar.dart
  lib/ui/_widgets/app_title.dart
  lib/ui/_widgets/octo_cat.dart
  lib/ui/_widgets/page_title.dart
  lib/ui/_widgets/text_link.dart
  lib/ui/home/home_view.dart
  lib/ui/login/oauth/login_oauth_screen.dart
  lib/ui/login/oauth/login_oauth_view.dart
  lib/ui/login/oauth/login_oauth_view_model.dart
  lib/ui/login/token/login_token_view.dart
  lib/ui/login/token/widgets/login_token_input.dart
  lib/ui/welcome/welcome_view.dart
  lib/utility/github_oauth_handler.dart
  test/utility/token_handler_test.dart
  test/widget_test.dart
Labels: 🛠️ Maintenance, 💬 Discussion

#45 :art: Upgrade UI for clarity
  lib/ui/login/oauth/login_oauth_view.dart
  lib/ui/login/token/widgets/login_token_input.dart
Labels: ♻️ Refactor, 🎨 UI/UX

#48 👷 Add workflow dispatch trigger to build.yml
  .github/workflows/build.yml
Labels: 🛠️ Maintenance

#49 👷 Add find and replace
  .github/workflows/build.yml
Labels: 🛠️ Maintenance

#50 Merge main into feature/home-screen
  .github/workflows/build.yml
Labels: 🛠️ Maintenance

#51 👷 Add working rename job
  .github/workflows/build.yml
Labels: 🛠️ Maintenance

#52 Merge main in feature/home-screen
  .github/workflows/build.yml
Labels: ♻️ Refactor

#53 ♻️ Rename artifacts with a better name
  .github/workflows/build.yml
Labels: 🛠️ Maintenance

#54 👷 Use dynamic branch for checkout
  .github/workflows/build.yml
Labels: 🛠️ Maintenance
