Repository RubberDuckCrew/gitdone, pull requests merged in 2025-09, with the labels that each got.

#212 👷 Fix enforce branch names inputs
  .github/workflows/conventions.yml
Labels: 🐛 Bug, 👷 CI/CD

#211 📝 Setup vitepress documentation
  .github/workflows/docs.yml
  .gitignore
  docs/.vitepress/config.ts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/style.css
  docs/package-lock.json
  docs/package.json
  docs/public/favicon.ico
  docs/public/logo.svg
  docs/src/contributing.md
  docs/src/development/app-icon-generation.md
  docs/src/index.md
Labels: 📝 Documentation, 👷 CI/CD

#199 ✨ Delete tasks
  lib/core/models/task.dart
  lib/core/task_handler.dart
  lib/core/utils/snack_bar.dart
  lib/ui/_widgets/app_bar.dart
  lib/ui/_widgets/confirm_dialog.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_view.dart
  lib/ui/task_details/task_details_view.dart
  lib/ui/task_details/task_details_view_model.dart
  pubspec.lock
Labels: ✨ Enhancement

#224 👷 Fix artifact names in post tagged
  .github/workflows/test-build-release.yml
Labels: 👷 CI/CD

#240 :arrow_up: Bump/Pin dependencies and update Flutter SDK version
  .github/workflows/test-build-release.yml
  pubspec.lock
  pubspec.yaml
Labels: 🔧 Configuration, 👷 CI/CD

#243 🔧 Move flutter version from actions to pubspec.yaml
  .github/workflows/test-build-release.yml
  pubspec.lock
  pubspec.yaml
Labels: 🔧 Configuration, 👷 CI/CD

#248 :arrow_up: Upgrade Flutter SDK version to 3.35.4
  pubspec.lock
  pubspec.yaml
Labels: 🔧 Configuration, 👷 CI/CD

#242 🔧 Migrate gradle from groovy to kotlin
  android/app/build.gradle.kts
  android/build.gradle
  android/build.gradle.kts
  android/settings.gradle
  android/settings.gradle.kts
Labels: 🔧 Configuration

#246 👷 Use centralized close actions
  .github/workflows/close-actions.yml
Labels: 👷 CI/CD

#257 ✨ Add settings handler
  lib/app_environment.dart
  lib/core/settings_handler.dart
  lib/core/task_handler.dart
  lib/main.dart
  lib/ui/settings/settings_view.dart
  lib/ui/settings/widgets/import_export/import_export_settings.dart
  lib/ui/settings/widgets/import_export/import_export_settings_view_model.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_model.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_view.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_view_model.dart
  lib/ui/task_list/task_list_view_model.dart
  lib/ui/welcome/welcome_view.dart
Labels: ✨ Enhancement

#264 📝 Document logging and dependency injection
  docs/.vitepress/config.ts
  docs/src/development/concepts/dependency-injection.md
  docs/src/development/concepts/logging.md
  docs/src/development/concepts/mvvm.md
Labels: 📝 Documentation

#265 🔒 Update signing key and publish public key
  .github/workflows/test-build-release.yml
  assets/keys/gitdone-certificate.pem
  docs/.vitepress/config.ts
  docs/src/download/index.md
  docs/src/download/verify.md
Labels: 📝 Documentation, 🔒️ Security
