Repository RubberDuckCrew/gitdone, pull requests merged in 2025-05, with the labels that each got.

#58 📝 Add contributors to README.md
  README.md
Labels: 📝 Documentation

#55 ✨ Improve home screen
  lib/app.dart
  lib/core/theme/app_color.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_screen_view_model.dart
  lib/ui/home/widgets/dropdown_filter_chip.dart
  lib/ui/login/oauth/login_oauth_view_model.dart
  lib/ui/login/token/widgets/login_token_input.dart
  lib/ui/settings/settings_view.dart
Labels: ✨ Enhancement

#61 🧑‍💻 Improve logging
  lib/core/models/github_oauth_model.dart
  lib/core/utils/logger.dart
Labels: 🛠️ Maintenance

#65 🧑‍💻 Update renovate.json
  .github/renovate.json
Labels: 🛠️ Maintenance

#66 👷 Add request-build action
  .github/labels.yml
  .github/renovate.json
  .github/workflows/request-build.yml
Labels: 🛠️ Maintenance

#73 👷 Add jdk setup to request build
  .github/workflows/request-build.yml
Labels: 🛠️ Maintenance

#77 ⬆️ Upgrade to Dart 3.7.2
  lib/app.dart
  lib/app_config.dart
  lib/core/github_api_handler.dart
  lib/core/models/github_oauth_model.dart
  lib/core/utils/logger.dart
  lib/ui/_widgets/app_bar.dart
  lib/ui/_widgets/app_title.dart
  lib/ui/_widgets/octo_cat.dart
  lib/ui/_widgets/text_link.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_view.dart
  lib/ui/home/widgets/dropdown_filter_chip.dart
  lib/ui/login/oauth/login_oauth_screen.dart
  lib/ui/login/oauth/login_oauth_view.dart
  lib/ui/login/oauth/login_oauth_view_model.dart
  lib/ui/login/token/login_token_view.dart
  lib/ui/login/token/widgets/login_token_input.dart
  lib/ui/welcome/welcome_view.dart
  pubspec.yaml
  test/utility/token_handler_test.dart
Labels: 🛠️ Maintenance

#78 ✨ Display version infos in app
  .github/workflows/build.yml
  .github/workflows/request-build.yml
  android/app/build.gradle
  lib/app_config.dart
  lib/main.dart
  lib/ui/welcome/welcome_view.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Enhancement

#81 👷 Auto remove work in process label from closed issues and PRs
  .github/workflows/close-actions.yml
Labels: 🛠️ Maintenance

#84 💚 Fix close-actions.yml permissions
  .github/workflows/close-actions.yml
Labels: 🚑️ Hotfix

#86 👷 Update close-actions.yml
  .github/workflows/close-actions.yml
Labels: 🛠️ Maintenance

#87 :construction_worker: Add branch naming enforcement configuration
  .github/branches.yml
  .github/workflows/enforce-branch-names.yml
Labels: 🛠️ Maintenance

#67 :sparkles: Add managment repo
  lib/core/models/repository_details.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_view.dart
  lib/ui/settings/settings_view.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_model.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_view.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Enhancement, 🚧 Work in Progress

#90 💚 Fix renovate pipelines
  .github/branches.yml
  .github/renovate.json
Labels: 🚑️ Hotfix

#93 :ambulance: Save selected repository on change in repository selector
  lib/ui/settings/widgets/repository_selector/repository_selector_view.dart
Labels: 🚑️ Hotfix

#94 👷 Simplify and update workflows
  .github/workflows/close-actions.yml
  .github/workflows/enforce-branch-names.yml
  .github/workflows/enforce-conventions.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/sync-labels.yml
Labels: 🛠️ Maintenance

#95 💚 Fix sparse-checkout misspelling
  .github/workflows/enforce-conventions.yml
  .github/workflows/sync-labels.yml
Labels: 🚑️ Hotfix

#96 :construction_worker: Enable wildcard usage
  .github/workflows/enforce-conventions.yml
Labels: 🛠️ Maintenance

#97 👷 Completely refactor build process
  .github/workflows/build.yml
  .github/workflows/request-build.yml
  .github/workflows/test-build-release.yml
  .github/workflows/test.yml
Labels: ♻️ Refactor

#92 💄 Improve settings view ui
  lib/core/models/current_user_model.dart
  lib/core/models/github_model.dart
  lib/core/models/token_handler.dart
  lib/ui/settings/settings_view.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_model.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_view_model.dart
Labels: 🎨 UI/UX

#100 👷 Update artifact names
  .github/workflows/test-build-release.yml
Labels: 🛠️ Maintenance

#106 :construction_worker: Add obfuscation and symbol upload to build ci
  .github/workflows/test-build-release.yml
Labels: 🛠️ Maintenance

#107 👷 Add osv-scanner.yml
  .github/workflows/osv-scanner.yml
Labels: 🛠️ Maintenance, 🔒️ Security

#108 👷 Add scheduled scanning
  .github/workflows/osv-scanner.yml
Labels: 🛠️ Maintenance, 🔒️ Security

#111 🔥 Remove build number from pubspec.yml
  pubspec.yaml
Labels: 🛠️ Maintenance

#112 👷 Disallow build on fork branch
  .github/workflows/test-build-release.yml
Labels: 👷 CI/CD

#109 :wrench: Update linter options
  analysis_options.yaml
  lib/app.dart
  lib/app_config.dart
  lib/core/github_api_handler.dart
  lib/core/models/current_user_model.dart
  lib/core/models/github_model.dart
  lib/core/models/github_oauth_model.dart
  lib/core/models/repository_details.dart
  lib/core/models/token_handler.dart
  lib/core/theme/app_color.dart
  lib/core/utils/logger.dart
  lib/main.dart
  lib/ui/_widgets/app_bar.dart
  lib/ui/_widgets/app_title.dart
  lib/ui/_widgets/octo_cat.dart
  lib/ui/_widgets/page_title.dart
  lib/ui/_widgets/text_link.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_screen_view_model.dart
  lib/ui/home/home_view.dart
  lib/ui/home/widgets/dropdown_filter_chip.dart
  lib/ui/login/oauth/login_oauth_screen.dart
  lib/ui/login/oauth/login_oauth_view.dart
  lib/ui/login/oauth/login_oauth_view_model.dart
  lib/ui/login/token/login_token_view.dart
  lib/ui/login/token/widgets/login_token_input.dart
  lib/ui/settings/settings_view.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_model.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_view.dart
  lib/ui/settings/widgets/repository_selector/repository_selector_view_model.dart
  lib/ui/welcome/welcome_view.dart
  test/utility/token_handler_test.dart
Labels: 🛠️ Maintenance
